// <auto-generated />
namespace AkaraProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig05 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig05));
        
        string IMigrationMetadata.Id
        {
            get { return "202105162343154_mig05"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
